services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - sene-network
  homebrewery:
    build:
      context: .
      dockerfile: Dockerfile
    image: homebrewery
    environment:
      MONGODB_URI: mongodb://mongodb/homebrewery
    networks:
      - sene-network
  nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - homebrewery
    networks:
      - sene-network
volumes:
  mongodata:
networks:
  sene-network:
    external: true
